routes/web.php
<?php

use App\Http\Middleware\CheckGuest;
use App\Http\Middleware\StoreScrollPosition;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::put('/absence/update', [App\Http\Controllers\AbsenceController::class, 'updateForStudent'])->name('absence.updateForStudent');
Route::get('/students/absence/OKJ', [App\Http\Controllers\AbsenceController::class, 'indexOKJ'])->name('students.absenceOKJ');
Route::get('/students/absence/11', [App\Http\Controllers\AbsenceController::class, 'index11'])->name('students.absence11');
Route::get('/students/absence/12', [App\Http\Controllers\AbsenceController::class, 'index12'])->name('students.absence12');

Route::get('/students', [App\Http\Controllers\StudentController::class, 'index'])->name('students.index');
Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();

Route::delete('workdays', [App\Http\Controllers\WorkDayController::class, 'destroy2'])->name('workdays.destroy2');
Route::resource('/workdays', App\Http\Controllers\WorkdayController::class);
Route::resource('/absence', App\Http\Controllers\AbsenceController::class);
Route::resource('/students', App\Http\Controllers\StudentController::class);

app/Models/WorkDay.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class WorkDay extends Model
{
    use HasFactory;

    protected $fillable = [
        'lesson_name',
        'day',
        'course_id',
    ];

    public function course(): BelongsTo{
        return $this->belongsTo(Course::class);
    }
}

app/Http/Controllers/WorkDayController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\DestroyWorkDayRequest;
use App\Http\Requests\ShowIndexRequest;
use App\Models\Absence;
use App\Models\Course;
use App\Models\Student;
use App\Models\WorkDay;
use App\Http\Requests\StoreWorkDayRequest;
use App\Http\Requests\UpdateWorkDayRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class WorkDayController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $workdays = WorkDay::all();
        return view('workdays.index', ['workdays' => $workdays]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(ShowIndexRequest $request)
    {
        $day = $request->day;
        $course_id = $request->course_id;
        $course = Course::all()->where('id', '=', $request->course_id)->value('name');
        if (count(DB::table('work_days')->where('course_id', '=', $course_id)->where('day', '=', $day)->get()) == 0) {
            return view('workdays.create', compact('day', 'course', 'course_id'));
        } else {
            return back()->with('fail', 'There\'s already a lesson for this day');
        }
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreWorkDayRequest $request, WorkDay $workday)
    {
        if (count(WorkDay::all()->where('day', '=', $request->day)->where('course_id', '=', $request->course_id)) > 0) {
            return redirect('/workdays')->with("fail", "Workday already created for this course");
        }
        $workday = new WorkDay([
            'lesson_name' => $request->lesson,
            'day' => $request->day,
            'course_id' => $request->course_id,
        ]);
        $workday->save();
        $filteredStudents = Student::all()->where('course_id', '=', $request->course_id);

        $filteredStudents->each(function ($student) use ($workday) {
            Absence::create([
                'workday_id' => $workday->id,
                'student_id' => $student->id,
            ]);
        });
        return redirect('/workdays')->with("success", "successfully created workday");
    }

    /**
     * Display the specified resource.
     */
    public function show(WorkDay $workDay)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(WorkDay $workDay)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateWorkDayRequest $request, WorkDay $workDay)
    {
        DB::update('UPDATE work_days SET lesson_name = "' . $request->lesson_name . '" WHERE id = ' . $request->workday_id . ' AND course_id = ' . $request->course_id);
        return back()->with('success', 'Lesson name updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy()
    {
        //
    }
    public function destroy2(DestroyWorkDayRequest $request)
    {
        // try {
            DB::table('work_days')->where('day', '=', $request->day)->where('course_id', '=', $request->course_id)->delete();
        // } catch (\Throwable $th) {
        //     return back()->with('fail', 'something went wrong');
        // }
        return back()->with('success', 'successfully deleted workday');
    }
}

resources/views/workdays/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-4"></div>
        <div class="col-4">

            <div class="card border-primary">
                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
                @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif


                <div class="card-body">
                    <h4 class="card-title">Add lesson for {{$day}} <br> <br>for the course: {{$course}}</h4>
                    <form action="{{ route('workdays.store') }}" method="post">
                        @csrf
                        @method('POST')
                        <div class="form-group p-5">
                            <div class="row">
                                <label for="name">Lesson Name</label>
                                <input type="text" name="lesson" id="lesson" class="form-control">
                                <input type="hidden" name="day" value="{{$day}}">
                                <input type="hidden" name="course_id" value="{{$course_id}}">
                            </div>
                            <div class="row d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-info w-50 text-white">Add Lesson</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


        </div>
        <div class="col-4"></div>

    </div>

@endsection

resources/views/workdays/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        td:hover {
            cursor: pointer;
        }

        .fc-daygrid-event-harness {
            z-index: -10000 !important;
        }

        /* The Modal (background) */
        .modal {
            display: none;
            /* Hidden by default */
            position: fixed;
            /* Stay in place */
            z-index: 1;
            /* Sit on top */
            left: 0;
            top: 0;
            width: 100%;
            /* Full width */
            height: 100%;
            /* Full height */
            overflow: auto;
            /* Enable scroll if needed */
            background-color: rgb(0, 0, 0);
            /* Fallback color */
            background-color: rgba(0, 0, 0, 0.4);
            /* Black w/ opacity */
        }

        /* Modal Content/Box */
        .modal-content {
            background-color: #fefefe;
            margin: 15% auto;
            /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 80%;
            /* Could be more or less, depending on screen size */
        }

        /* The Close Button */
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }

        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
    </style>
    @if(Session::has('fail'))
        <script>
            alert('ERROR! There\'s already a lesson for this day and course!')
        </script>
    @endif
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">

            <div id='calendar'></div>
            <!-- Cloudflare Pages Analytics -->
            <script defer src='https://static.cloudflareinsights.com/beacon.min.js'
                data-cf-beacon='{"token": "dc4641f860664c6e824b093274f50291"}'></script><!-- Cloudflare Pages Analytics -->

            <!-- Trigger/Open The Modal -->
            <button id="myBtn" style="display: none">Open Modal</button>

            <!-- The Modal -->
            <div id="myModal" class="modal">

                <!-- Modal content -->
                <div class="modal-content">
                    <span class="close">&times;</span>
                    <h4 id="titleForModal">View</h4>
                    <div class="row">
                        <div class="col-3"></div>
                        <div class="row">
                            <div class="col-3" id="tweedleDee1">
                                <form action="{{ route('students.absenceOKJ') }}" method="GET">
                                    <input type="hidden" name="day" id="day1">
                                    <button type="submit" class="btn btn-info" onclick="getDay1()">OKJ</button>
                                </form>
                            </div>
                            <div class="col-3" id="tweedleDee2">
                                <form action="{{ route('students.absence11') }}" method="GET">
                                    <input type="hidden" name="day" id="day2">
                                    <button type="submit" class="btn btn-info" onclick="getDay2()">11</button>
                                </form>
                            </div>
                            <div class="col-3" id="tweedleDee3">
                                <form action="{{ route('students.absence12') }}" method="GET">
                                    <input type="hidden" name="day" id="day3">
                                    <button type="submit" class="btn btn-info" onclick="getDay3()">12</button>
                                </form>
                            </div>
                        </div>

                        <h4 class="mt-5">Remove course</h4>
                        <div class="row">
                            <div class="col-3" id="tweedleDum1">
                                <form action="{{ route('workdays.destroy2') }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <input type="hidden" name="day" id="Tday1">
                                    <input type="hidden" name="course_id" value='1' id="course_id1">
                                    <button type="submit" class="btn btn-danger" onclick="TgetDay1()">OKJ</button>
                                </form>
                            </div>
                            <div class="col-3" id="tweedleDum2">
                                <form action="{{ route('workdays.destroy2') }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <input type="hidden" name="day" id="Tday2">
                                    <input type="hidden" name="course_id" value='2' id="course_id2">
                                    <button type="submit" class="btn btn-danger" onclick="TgetDay2()">11</button>
                                </form>
                            </div>
                            <div class="col-3" id="tweedleDum3">
                                <form action="{{ route('workdays.destroy2') }}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <input type="hidden" name="day" id="Tday3">
                                    <input type="hidden" name="course_id" value='3' id="course_id3">
                                    <button type="submit" class="btn btn-danger" onclick="TgetDay3()">12</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-3"></div>
            <script>
                // Get the modal
                var modal = document.getElementById("myModal");

                // Get the button that opens the modal
                var btn = document.getElementById("myBtn");

                // Get the <span> element that closes the modal
                var span = document.getElementsByClassName("close")[0];

                // When the user clicks on the button, open the modal
                btn.onclick = function() {
                    modal.style.display = "block";
                }

                // When the user clicks on <span> (x), close the modal
                span.onclick = function() {
                    modal.style.display = "none";
                }

                // When the user clicks anywhere outside of the modal, close it
                window.onclick = function(event) {
                    if (event.target == modal) {
                        modal.style.display = "none";
                    }
                }
                var dates = [];
                @foreach ($workdays as $workday)
                    @if ($workday->course_id == 1)
                        var obj = {
                            day: '{{ $workday->day }}',
                            course_id: 1,
                        };
                    @elseif ($workday->course_id == 2)
                        var obj = {
                            day: '{{ $workday->day }}',
                            course_id: 2,
                        };
                    @elseif ($workday->course_id == 3)
                        var obj = {
                            day: '{{ $workday->day }}',
                            course_id: 3,
                        };
                    @endif
                    dates.push(obj);
                @endforeach
                var select = "";

                document.addEventListener('DOMContentLoaded', function() {
                    var calendarEl = document.getElementById('calendar');
                    var calendar = new FullCalendar.Calendar(calendarEl, {
                        selectable: true,
                        headerToolbar: {
                            left: 'prev,next today',
                            center: 'title',
                            right: 'dayGridMonth'
                        },
                        events: [
                            @foreach ($workdays as $workday)
                                {

                                    title: '{{ $workday->course->name }}',
                                    allDay: true,
                                    start: '{{ $workday->day }}',
                                    end: null,
                                },
                            @endforeach
                        ],
                        dateClick: function(info) {
                            select = String(info.dateStr);
                            console.log(select);
                            btn.click();

                        },
                    });

                    calendar.render();
                });


                function getDay1() {
                    document.getElementById('day1').setAttribute('value', select);
                }

                function getDay2() {
                    document.getElementById('day2').setAttribute('value', select);
                }

                function getDay3() {
                    document.getElementById('day3').setAttribute('value', select);
                }


                function TgetDay1() {
                    document.getElementById('Tday1').setAttribute('value', select);
                }

                function TgetDay2() {
                    document.getElementById('Tday2').setAttribute('value', select);
                }

                function TgetDay3() {
                    document.getElementById('Tday3').setAttribute('value', select);
                }
            </script>
        </div>
    @endsection