routes/web.php
<?php

use App\Http\Middleware\CheckGuest;
use App\Http\Middleware\StoreScrollPosition;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::put('/absence/update', [App\Http\Controllers\AbsenceController::class, 'updateForStudent'])->name('absence.updateForStudent');
Route::get('/students/absence/OKJ', [App\Http\Controllers\AbsenceController::class, 'indexOKJ'])->name('students.absenceOKJ');
Route::get('/students/absence/11', [App\Http\Controllers\AbsenceController::class, 'index11'])->name('students.absence11');
Route::get('/students/absence/12', [App\Http\Controllers\AbsenceController::class, 'index12'])->name('students.absence12');

Route::get('/students', [App\Http\Controllers\StudentController::class, 'index'])->name('students.index');
Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();

Route::delete('workdays', [App\Http\Controllers\WorkDayController::class, 'destroy2'])->name('workdays.destroy2');
Route::resource('/workdays', App\Http\Controllers\WorkdayController::class);
Route::resource('/absence', App\Http\Controllers\AbsenceController::class);
Route::resource('/students', App\Http\Controllers\StudentController::class);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Student extends Model
{
    use HasFactory;
    use SoftDeletes;


    protected $fillable = [
        'name',
        'birthdate',
        'course_id',
        'created_by',
    ];

    public function course(): BelongsTo{
        return $this->belongsTo(Course::class);
    }

    public function absence(): HasMany{
        return $this->hasMany(Absence::class);
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Absence;
use App\Models\Student;
use App\Http\Requests\StoreStudentRequest;
use App\Http\Requests\UpdateStudentRequest;
use App\Models\WorkDay;
use Illuminate\Support\Facades\Auth;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $students = Student::all();
        return view('students.index', ['students' => $students]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        if(Auth::user()->role_id == 1){
            return view('students.create');
        }
        return abort(403);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreStudentRequest $request, Student $student)
    {
        if(Auth::user()->role_id == 1){
            $student = new Student(
                [
                    "name" => $request->name,
                    "birthdate" => $request->birthdate,
                    "course_id" => $request->course_id,
                    "created_by" => Auth::user()->id,
                ]
            );
    
            $student->save();
    
            return back()->with("success", "Student created successfully.");
    
        }
        return abort(403);
    }

    /**
     * Display the specified resource.
     */
    public function show(Student $student)
    {
        $absences = Absence::all()->where('student_id', '=', $student->id);
        $workdays = WorkDay::all()->where('course_id', '=', $student->course_id);
        return view('students.show', ['student' => $student], compact('absences', 'workdays'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Student $student)
    {
        return view('students.edit', ['student' => $student]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateStudentRequest $request, Student $student)
    {
        $student->update([
            "name" => $request->name,
            "birthdate" => $request->birthdate,
            "course_id" => $request->course_id,
            "updated_by" => Auth::user()->id,
        ]);
        return back()->with('success', 'Student updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Student $student)
    {
        if(Auth::user()->role_id == 1){
            $student->deleted_by = Auth::user()->id;
            $student->delete();
            return back()->with('success', 'Student deleted successfully');
        }
        return abort(403);
    }

    public function show_deleted(){
        if(Auth::user()->role_id == 1){
            $students = Student::onlyTrashed()->get();
            return view('students.show_deleted', ['students' => $students]);
        }
        return abort(403);
    }

    public function restore(Student $student){
        $student->restore();
        $student->updated_by = Auth::user();
        return back()->with('success', 'Student restored successfully');
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-4"></div>
        <div class="col-4">

            <div class="card border-primary">
                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
                @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif


                <div class="card-body">
                    <h4 class="card-title">Add student</h4>
                    <form action="{{ route('students.store') }}" method="post">
                        @csrf
                        @method('POST')
                        <div class="form-group p-5">
                            <div class="row">
                                <label for="name">Student's name</label>
                                <input type="text" name="name" id="name" class="form-control">
                            </div>
                            <div class="row mt-4">
                                <label for="birthdate">Student's date of birth</label>
                                <input type="date" name="birthdate" id="birthdate" class="form-control">
                            </div>
                            <div class="row mt-4">
                                <label for="course_id">Course</label>
                                <div>
                                    <input type="radio" id="course_id1" name="course_id" value="1" />
                                    <label for="course_id">OKJ</label>
                                  </div>
                                
                                  <div>
                                    <input type="radio" id="course_id2" name="course_id" value="2" />
                                    <label for="course_id">11.</label>
                                  </div>
                                
                                  <div>
                                    <input type="radio" id="course_id3" name="course_id" value="3" />
                                    <label for="course_id">12.</label>
                                  </div>
                            </div>
                            <div class="row d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-info w-50 text-white">Add student</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


        </div>
        <div class="col-4"></div>

    </div>

@endsection

resources/views/students/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">

        <div class="col-4"></div>
        <div class="col-4">

            <div class="card border-primary">
                @if ($errors->any())
                    <div class="mb-3 mt-3">
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                            <strong>Holy guacamole!</strong>

                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endif
                @if (Session::has('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                         
                            <strong>Holy guacamole!</strong> 
                            <p>{{Session::get('success')}}</p>
                        </div>
                    @endif


                <div class="card-body">
                    <h4 class="card-title">Edit student: {{$student->name}}</h4>
                    <form action="{{ route('students.update', $student) }}" method="post">
                        @csrf
                        @method('PUT')
                        <div class="form-group p-5">
                            <div class="row">
                                <label for="name">Student's name</label>
                                <input type="text" name="name" id="name" class="form-control" value="{{old('name', $student->name)}}">
                            </div>
                            <div class="row mt-4">
                                <label for="birthdate">Student's date of birth</label>
                                <input type="date" name="birthdate" id="birthdate" class="form-control" value="{{old('birthdate', $student->birthdate)}}">
                            </div>
                            <div class="row mt-4">
                                <label for="course_id">Course</label>
                                <div>
                                    <input type="radio" id="course_id1" name="course_id" value="1" @if($student->course_id == 1) checked @endif/>
                                    <label for="course_id">OKJ</label>
                                  </div>
                                
                                  <div>
                                    <input type="radio" id="course_id2" name="course_id" value="2" @if($student->course_id == 2) checked @endif/>
                                    <label for="course_id">11.</label>
                                  </div>
                                
                                  <div>
                                    <input type="radio" id="course_id3" name="course_id" value="3" @if($student->course_id == 3) checked @endif/>
                                    <label for="course_id">12.</label>
                                  </div>
                            </div>
                            <div class="row d-flex justify-content-center mt-5">
                                <button type="submit" class="btn btn-info w-50 text-white">Edit student</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>


        </div>
        <div class="col-4"></div>

    </div>

@endsection

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
    <style>
        .table-responsive {
            overflow: hidden !important;
        }

        .dataTables_length {
            display: none;
        }
    </style>
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">

            <div class="table-responsive">
                <table class="table table-primary" id="myTable">
                    <thead>
                        <tr>
                            <th scope="col">Student name</th>
                            <th scope="col">Student birthdate</th>
                            <th scope="col">Student course</th>
                            <th scope="col" data-orderable="false">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($students as $student)
                            <tr>
                                <td>{{ $student->name }}</td>
                                <td>{{ $student->birthdate }}</td>
                                <td>{{ $student->course->name }}</td>
                                <td class="d-flex">
                                    <form action="{{ route('students.show', $student) }}" method="get">
                                        <button type="submit" class="btn btn-info me-5">Show</button>
                                    </form>
                                    <form action="{{ route('students.edit', $student) }}" method="get">
                                        <button type="submit" class="btn btn-warning ms-5 me-5">Edit</button>
                                    </form>
                                    <form action="{{ route('students.destroy', $student) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger ms-5">Delete</button>
                                    </form>

                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
    <script>
        let table = new DataTable('#myTable', {
            stateSave: true,
            iDisplayLength: 100,
        });
    </script>
@endsection

resources/views/students/show.blade.php
@extends('layouts.app')

@section('content')
    <style>
        td:hover {
            cursor: pointer;
        }

        #Present {
            background-color: green;
        }

        html,
        body {
            margin: 0;
            padding: 0;
            font-family: Arial, Helvetica Neue, Helvetica, sans-serif;
            font-size: 14px;
        }

        #external-events {
            z-index: 2;
            width: 300px;
            padding: 0 10px;
            border: 1px solid #ccc;
            background: #eee;
        }

        #external-events .fc-event {
            cursor: move;
            margin: 3px 0;
        }

        #calendar-container {
            position: relative;
            z-index: 1;
            margin-left: 200px;
        }

        #calendar {
            max-width: 1100px;
            margin: 20px auto;
        }
    </style>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var Calendar = FullCalendar.Calendar;
            var Draggable = FullCalendar.Draggable;

            var containerEl = document.getElementById('external-events');
            var calendarEl = document.getElementById('calendar');
            var checkbox = document.getElementById('drop-remove');

            // initialize the external events
            // -----------------------------------------------------------------

            new Draggable(containerEl, {
                itemSelector: '#Present',
                eventData: function(eventEl) {
                    return {
                        id: "present",
                        color: 'green',
                        title: eventEl.innerText,
                    };
                }
            });
            new Draggable(containerEl, {
                itemSelector: '#Sick',
                eventData: function(eventEl) {
                    return {
                        id: 'sick',
                        color: 'yellow',
                        title: eventEl.innerText,
                    };
                }
            });
            new Draggable(containerEl, {
                itemSelector: '#Absent',
                eventData: function(eventEl) {
                    return {
                        id: "absent",
                        color: 'red',
                        title: eventEl.innerText,
                    };
                }
            });

            // initialize the calendar
            // -----------------------------------------------------------------
            var eventColor;
            var calendar = new Calendar(calendarEl, {
                headerToolbar: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'dayGridMonth'
                },
                selectable: true,
                droppable: true, // this allows things to be dropped onto the calendar
                events: [
                    @foreach ($absences as $absence)
                        {

                            title: '{{ $absence->status }}',
                            allDay: true,
                            color: changeColor('{{ $absence->status }}'),
                            start: '{{ $workdays->where('id', '=', $absence->workday_id)->value('day') }}',
                            end: null,
                        },
                    @endforeach
                ],
                drop: function(info) {
                    var events = calendar.getEvents();
                    for (var event of events) {
                        if (event.startStr == info.dateStr) {
                            event.remove();
                            break;
                        }
                    }
                    console.log(info.draggedEl.id);
                    callTheFormSubmission(info);
                }
            });
            function callTheFormSubmission(info){
                document.getElementById('day').setAttribute('value', info.dateStr);
                document.getElementById('status').setAttribute('value', info.draggedEl.id);
                console.log(info.dateStr);
                console.log(info.draggedEl.id);
                document.getElementById('formBtn').click();
            }
            
            function changeColor(status) {
                if (status == "Present") {
                    return 'green';
                } else if (status == "Absent") {
                    return 'red';
                } else {
                    return 'yellow';
                }
            }


            calendar.render();
        });
    </script>
    @if (Session::has('fail'))
        <script>
            alert('This day doesn\'t have a lesson!');
        </script>
    @endif
    <div class="row">

        <div class="col-3"></div>
        <div class="col-6">

            <div class="card border-primary">
                <div class="card-body">
                    <h4 class="card-title">{{ $student->name }}</h4>
                    <p class="card-text">{{ $student->birthdate }}</p>
                    <p class="card-text">{{ $student->course->name }}</p>
                </div>



            </div>
            <div class="col-3"></div>


        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-2 mt-5">
            <div id='external-events'>
                <p>
                    <strong>Draggable Events</strong>
                </p>

                <div class='fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event bg-success' id="Present">
                    <div class='fc-event-main'>Present</div>
                </div>
                <div class='fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event bg-warning' id="Sick">
                    <div class='fc-event-main'>Sick</div>
                </div>
                <div class='fc-event fc-h-event fc-daygrid-event fc-daygrid-block-event bg-danger' id="Absent">
                    <div class='fc-event-main'>Absent</div>
                </div>
                <p style="display: none">
                    <input type='checkbox' id='drop-remove' />
                </p>
            </div>
        </div>
        <div class="col-8">
            <div id='calendar-container'>
                <div id='calendar'></div>
                <form action="{{route('absence.updateForStudent', $student)}}" method="POST">
                    @csrf
                    @method('PUT')
                    <input type="hidden" name="day" id="day">
                    <input type="hidden" name="status" id="status">
                    <input type="hidden" name="student_id" value="{{$student->id}}">
                    <input type="hidden" name="course_id" value="{{$student->course_id}}">
                    <button type="submit" class="d-none" id="formBtn"></button>
                </form>
            </div>

            <!-- Cloudflare Pages Analytics -->
            <script defer src='https://static.cloudflareinsights.com/beacon.min.js'
                data-cf-beacon='{"token": "dc4641f860664c6e824b093274f50291"}'></script><!-- Cloudflare Pages Analytics -->

        </div>
        @foreach ($absences as $absence)
            <script>
                var dateStatus = document.querySelector(
                    '[data-date="{{ $workdays->where('id', '=', $absence->workday_id)->value('day') }}"]');
                var event = {
                    id: '{{ $absence->status }}',
                    title: '{{ $absence->status }}',
                    start: {
                        date: '{{ $workdays->where('id', '=', $absence->workday_id)->value('day') }}',
                    },
                    end: {
                        date: '{{ $workdays->where('id', '=', $absence->workday_id)->value('day') }}',
                    }
                };
                var Calendar = FullCalendar.Calendar;
                var calendarEl = $('#calendar');
                var calendar = new Calendar(calendarEl, {
                    timeZone: 'UTC',
                    events: [{
                        id: '{{ $absence->status }}',
                        title: '{{ $absence->status }}',
                        allDay: true,
                    }]
                })
            </script>
        @endforeach
    </div>
@endsection

resources/views/students/show_deleted.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">

            <div class="table-responsive">
                <table class="table table-primary">
                    <thead>
                        <tr>
                            <th scope="col">Student name</th>
                            <th scope="col">Student birthdate</th>
                            <th scope="col">Student course</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($students as $student)
                            <tr>
                                <td>{{ $student->name }}</td>
                                <td>{{ $student->birthdate }}</td>
                                <td>{{ $student->course->name }}</td>
                                <td class="d-flex">
                                    <form action="{{ route('students.restore', $student) }}" method="post">
                                        @csrf
                                        @method('PUT')
                                        <button type="submit" class="btn btn-info me-5">Restore</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>

        </div>
        <div class="col-2"></div>
    </div>
@endsection