routes/web.php
<?php

use App\Http\Middleware\CheckGuest;
use App\Http\Middleware\StoreScrollPosition;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('home');
});

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
*/

Route::put('/absence/update', [App\Http\Controllers\AbsenceController::class, 'updateForStudent'])->name('absence.updateForStudent');
Route::get('/students/absence/OKJ', [App\Http\Controllers\AbsenceController::class, 'indexOKJ'])->name('students.absenceOKJ');
Route::get('/students/absence/11', [App\Http\Controllers\AbsenceController::class, 'index11'])->name('students.absence11');
Route::get('/students/absence/12', [App\Http\Controllers\AbsenceController::class, 'index12'])->name('students.absence12');

Route::get('/students', [App\Http\Controllers\StudentController::class, 'index'])->name('students.index');
Route::get('/students/show_deleted', [App\Http\Controllers\StudentController::class, 'show_deleted'])->name('students.show_deleted');
Route::put('/students/restore/{student}', [App\Http\Controllers\StudentController::class, 'restore'])->name('students.restore')->withTrashed();

Route::delete('workdays', [App\Http\Controllers\WorkDayController::class, 'destroy2'])->name('workdays.destroy2');
Route::resource('/workdays', App\Http\Controllers\WorkdayController::class);
Route::resource('/absence', App\Http\Controllers\AbsenceController::class);
Route::resource('/students', App\Http\Controllers\StudentController::class);

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=Nunito" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <link href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"></script>

    <script src='https://cdn.jsdelivr.net/npm/fullcalendar@6.1.10/index.global.min.js'></script>
    {{-- <script>
        document.addEventListener('DOMContentLoaded', function() {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: 'dayGridMonth'
            });
            calendar.render();
        });
    </script> --}}

    <!-- Scripts -->
    @vite(['resources/sass/app.scss', 'resources/js/app.js'])

    @vite(['resources/sass/app.scss', 'resources/css/app.css'])
</head>

<body>
    <style>
        .dropdown-menu {
            background-color: white;
        }

        .dropdown-menu a {
            background-color: white;
            transition: all 0.1s ease-in-out;
        }

        .dropdown-menu a:hover {
            background-color: rgba(0, 0, 0, 0.1);
        }
    </style>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item nav-dropdown" href="{{ route('students.index') }}">
                                        Students
                                    </a>
                                    <a class="dropdown-item nav-dropdown" href="{{ route('workdays.index') }}">
                                        Calendar
                                    </a>
                                    <h5 class="dropdown-item nav-dropdown">Moderation (Admin Only)</h5>
                                    <a class="dropdown-item nav-dropdown" href="{{ route('students.create') }}">
                                        Add student
                                    </a>
                                    <a class="dropdown-item nav-dropdown" href="{{ route('students.show_deleted') }}">
                                        Deleted students
                                    </a>
                                    <hr>
                                    <a class="dropdown-item nav-dropdown" href="{{ route('logout') }}"
                                        onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>

                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>

</html>